use_lockfile = false

[project]
name = "hyperion.tables"
r_version = "4.5"

repositories = [
  { alias = "prism", url = "https://prism.dev.a2-ai.cloud/rpkgs/stratus/2026-01-14" },
  { alias = "ppm", url = "https://packagemanager.posit.co/cran/latest" },
  { alias = "CRAN", url = "https://cran.r-project.org" },
]

dependencies = [
	# dev dependencies
  "devtools",
  { name = "covr", install_suggestions = true },
  { name = "starlightr", git = "https://github.com/a2-ai/starlightr", branch = "main" },
	
	# package deps
	{ name = "hyperion", git = "https://github.com/a2-ai/hyperion", branch = "transforms-mod" },
  { name = "hyperion.tables", path = ".", dependencies_only = true, install_suggestions = true },
]
