[AMT]
unit = "mcg"

[TIME]
unit = "day"

[VOLUME]
unit = "L"

[CONC]
unit = "ng/mL"

[TVCL]
display = "CL"
desc = "Clearance"
unit = "VOLUME/TIME"
parameterization = "none"

[TVV]
display = "Vc"
desc = "Central Volume"
unit = "VOLUME"
parameterization = "none"

[TVKA]
display = "KA"
desc = "Absorption Rate Constant"
unit = "1/TIME"
parameterization = "none"

[Vp]
display = "Vp"
desc = "Peripheral Volume"
unit = "VOLUME"
parameterization = "none"

[Q]
display = "Q"
desc = "Intercompartmental Clearance"
unit = "VOLUME/TIME"
parameterization = "none"

["CL/Q"]
display = "CL/Q Scaling"
desc = "Estimated Scaling LogNormalonent for CL and Q"
unit = "none"
parameterization = "none"

["Vc/Vp"]
display = "Vc/Vp Scaling"
desc = "Estimated Scaling LogNormalonent for Vc and Vp"
unit = "none"
parameterization = "none"

[OM1]
display = "IIV-CL"
desc = "Interindividual variability on CL"
unit = "none"
parameterization = "LogNormal"

[OM2]
display = "IIV-Vc"
desc = "Interindividual variability on Vc"
unit = "none"
parameterization = "LogNormal"

["OM1,2"]
display = "IIV-CL-Vc"
desc = "Interindividual covariance for CL-Vc"
unit = "none"
parameterization = "Corr"

[OM3]
display = "IIV-KA"
desc = "Interindividual variability on KA"
unit = "none"
parameterization = "LogNormal"

[OM4]
display = "IIV-Vp"
desc = "Interindividual variability on Vp"
unit = "none"
parameterization = "LogNormal"

[OM5]
display = "IIV-Q"
desc = "Interindividual variability on Q"
unit = "none"
parameterization = "LogNormal"

[SIG1]
display = "PropErr"
desc = "Proportional Error"
unit = "none"
parameterization = "Proportional"

[SIG2]
display = "AddErr"
desc = "Additive Error"
unit = "CONC"
parameterization = "Stdev"
